// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, Calendar, CheckCircle, Search, Shield, Sparkles, Truck } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="About Us"
          title="Mobile Detailing Excellence"
          description="We bring premium detailing tools, eco-friendly products and years of experience directly to your door, treating every vehicle with the care of an enthusiast."
          items={[
            {
              icon: CheckCircle,
              title: "Mobile First",
              description: "We come to your convenience.",
            },
            {
              icon: Shield,
              title: "Insured & Certified",
              description: "Peace of mind for your vehicle.",
            },
            {
              icon: Sparkles,
              title: "High-Quality Products",
              description: "Premium supplies for superior results.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/asian-man-wear-all-black-posed-near-suv-car-smoke-hookah_627829-3706.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
