// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="FAQ"
          title="Common Questions"
          description="Answers to your queries regarding our mobile services and booking process."
          items={[
            {
              question: "What areas do you cover?",
              answer: "We provide mobile services within a 20-mile radius of our base. Please contact us to confirm your postcode.",
            },
            {
              question: "Do I need to provide water/power?",
              answer: "We are fully self-sufficient. We carry our own high-quality water and electricity supply.",
            },
            {
              question: "How long does a valet take?",
              answer: "Depending on the service, usually between 2 to 6 hours for a full detail.",
            },
            {
              question: "Can you work at my office?",
              answer: "Yes, as long as we have sufficient space and permission, we can work at your workplace.",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
