// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardBrand from '@/components/sections/hero/HeroBillboardBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardBrand
          brand="Premium Mobile Car Valeting & Detailing"
          description="Professional vehicle care brought directly to you. Expert attention to every detail."
          primaryButton={{
            text: "Get A Quote",
            href: "#quote",
          }}
          secondaryButton={{
            text: "View Our Work",
            href: "#work",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/stylish-rear-light-new-dark-auto_23-2147963019.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
