// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "quote" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function QuoteSection(): React.JSX.Element {
  return (
    <div id="quote" data-section="quote">
        <SectionErrorBoundary name="quote">
              <ContactCta
        tag="Get A Quote"
        text="Ready to give your car the finish it deserves? Request a quote for your vehicle today."
        primaryButton={{
            text: "REQUEST A QUOTE",
            href: "#",
          }}
        secondaryButton={{"text":"Message WhatsApp","href":"https://wa.me/447802167343?text=Hi%20Quality%20Car%20Valeting%2C%20I%27d%20like%20to%20enquire%20about%20booking%20a%20valet."}}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
