// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "quote" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function QuoteSection(): React.JSX.Element {
  return (
    <div id="quote" data-section="quote">
        <SectionErrorBoundary name="quote">
              <ContactCta
          tag="Get A Quote"
          text="Ready to give your car the finish it deserves? Request a quote for your vehicle today."
          primaryButton={{
            text: "REQUEST A QUOTE",
            href: "#",
          }}
          secondaryButton={{
            text: "Message WhatsApp",
            href: "https://wa.me/123456789",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
