// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "reviews" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ReviewsSection(): React.JSX.Element {
  return (
    <div id="reviews" data-section="reviews">
        <SectionErrorBoundary name="reviews">
              <TestimonialQuoteCards
          tag="Reviews"
          title="Client Success Stories"
          description="Genuine feedback from local customers who trust their vehicles to our expertise."
          testimonials={[
            {
              name: "John D.",
              role: "Luxury Sedan Owner",
              quote: "The best mobile detail I have ever had. The attention to detail is truly incredible.",
              imageSrc: "http://img.b2bpic.net/free-photo/mechanic-with-protective-face-mask-standing-auto-repair-shop-looking-camera_637285-11579.jpg",
            },
            {
              name: "Sarah M.",
              role: "Family SUV Owner",
              quote: "Convenient, professional and my car looks brand new again. Highly recommended.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-man-choosing-car-car-showroom_1303-21752.jpg",
            },
            {
              name: "David L.",
              role: "Sports Car Enthusiast",
              quote: "Expert paint correction. The finish on my paintwork is flawless.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-happy-smiling-man-who-chooses-new-car-cabin_146671-19461.jpg",
            },
            {
              name: "Emma R.",
              role: "Business Owner",
              quote: "Great service at my workplace. Very convenient for a busy professional.",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-enjoying-her-financially-independence-while-buying-car_23-2149434350.jpg",
            },
            {
              name: "Mark S.",
              role: "Regular Client",
              quote: "Professional, punctual and reliable. Best mobile service in the area.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-handsome-man-car-showroom_1303-17460.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
