/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";
import Button from "@/components/ui/Button";
import { cls } from "@/lib/utils";
import { Camera } from "lucide-react";

const features = [
  {
    id: "wash-shammy",
    title: "Wash & Shammy",
    description: "Hand wash and shammy dry for a streak-free exterior clean, brought directly to you.",
    imageSrc: ""
  },
  {
    id: "basic-valet",
    title: "Basic Valet",
    description: "Quick, thorough exterior wash and interior freshen-up for everyday vehicle care.",
    imageSrc: ""
  },
  {
    id: "standard-valet",
    title: "Standard Valet",
    description: "Comprehensive care including full exterior wash and thorough interior vacuuming and wipe-down.",
    imageSrc: ""
  },
  {
    id: "full-valet",
    title: "Full Valet",
    description: "Complete interior and exterior mobile valet leaving your car thoroughly refreshed.",
    imageSrc: ""
  },
  {
    id: "interior-valet",
    title: "Interior Valet",
    description: "Focused interior deep clean covering seats, carpets, dashboard, and cabin surfaces.",
    imageSrc: ""
  },
  {
    id: "regular-valets",
    title: "Weekly & Monthly Valets",
    description: "Regular scheduled maintenance valets to keep your vehicle spotless on an ongoing basis.",
    imageSrc: ""
  },
  {
    id: "exterior-polish",
    title: "Exterior Polish Including Mopping",
    description: "Quality hand polish and exterior mopping using top products to restore a deep shine.",
    imageSrc: ""
  }
];
const primaryButton = {
  text: "Get A Quote",
  href: "#quote"
};

type FeatureItem = {
  title: string;
  description: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesBentoGridProps {
  tag: string;
  title: string;
  description: string;
  features: [FeatureItem, FeatureItem, FeatureItem, FeatureItem];
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const ServicesInline = () => {
  const colSpans = ["md:col-span-5", "md:col-span-7", "md:col-span-7", "md:col-span-5"];

  return (
    <section aria-label="Features section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Services"}</p>
          </div>

          <TextAnimation
            text={"Comprehensive Detailing"}
            variant={"fade"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Tailored packages designed to maintain and protect your vehicle’s aesthetic value."}
            variant={"fade"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(primaryButton || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {primaryButton && <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="fade-blur" className="w-content-width mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature) => (
              <div key={feature.title} className="flex flex-col justify-between gap-4 p-5 card rounded-xl border border-foreground/10">
                <div className="flex flex-col gap-4">
                  <div className="aspect-video w-full rounded-lg overflow-hidden bg-foreground/5 border border-foreground/10 flex flex-col items-center justify-center text-accent">
                    {feature.imageSrc ? (
                      <ImageOrVideo imageSrc={feature.imageSrc} />
                    ) : (
                      <div className="flex flex-col items-center gap-2 p-4 text-center">
                        <div className="p-2.5 rounded-full bg-foreground/5 border border-foreground/10 text-foreground/70">
                          <Camera className="w-5 h-5" />
                        </div>
                        <span className="text-xs font-medium tracking-wide uppercase text-accent/80">Photo Placeholder</span>
                      </div>
                    )}
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <h3 className="text-xl font-semibold leading-snug text-foreground">{feature.title}</h3>
                    <p className="text-sm text-accent leading-relaxed">{feature.description}</p>
                  </div>
                </div>
                <div className="pt-3 border-t border-foreground/10">
                  <a href="#quote" className="inline-flex items-center justify-center w-full py-2.5 px-4 text-sm font-semibold rounded primary-button">
                    Get A Quote
                  </a>
                </div>
              </div>
            ))}
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
