// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-us" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, Calendar, CheckCircle, Search, Shield, Sparkles, Truck } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WhyUsSection(): React.JSX.Element {
  return (
    <div id="why-us" data-section="why-us">
        <SectionErrorBoundary name="why-us">
              <AboutFeaturesSplit
          tag="Why Us"
          title="Unrivalled Vehicle Care"
          description="We blend convenience with professional-grade detailing techniques to ensure your vehicle looks as good as the day it left the showroom."
          items={[
            {
              icon: Truck,
              title: "We Come To You",
              description: "Professional care at your home or workplace.",
            },
            {
              icon: Search,
              title: "Attention To Detail",
              description: "Every nook and cranny meticulously cleaned.",
            },
            {
              icon: Award,
              title: "Professional Finish",
              description: "Excellence in every polish and protection.",
            },
            {
              icon: Calendar,
              title: "Convenient Booking",
              description: "Easy online scheduling for your busy life.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/close-up-car-care-process_23-2149193628.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
