// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "work" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WorkSection(): React.JSX.Element {
  return (
    <div id="work" data-section="work">
        <SectionErrorBoundary name="work">
              <FeaturesImageBento
          tag="Our Work"
          title="The Quality Difference"
          description="See the results of our dedication to vehicle aesthetics."
          items={[
            {
              title: "Interior Restoration",
              description: "Before & After",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-car-interior-with-steering-wheel-infotainment-system-screen_482257-118089.jpg",
            },
            {
              title: "Paint Correction",
              description: "Gloss finish",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-person-cleaning-car-exterior_23-2148194092.jpg",
            },
            {
              title: "Engine Bay Detail",
              description: "Clean finish",
              imageSrc: "http://img.b2bpic.net/free-photo/low-angle-woman-repairing-car_23-2150171283.jpg",
            },
            {
              title: "Leather Care",
              description: "Restored finish",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-car-interior-clean-up-service_23-2149212253.jpg",
            },
            {
              title: "Wheel Detailing",
              description: "Deep clean",
              imageSrc: "http://img.b2bpic.net/free-photo/man-wash-car-using-shampoo_1150-6983.jpg",
            },
            {
              title: "Exterior Protection",
              description: "Ceramic finish",
              imageSrc: "http://img.b2bpic.net/free-photo/person-working-car-wrapping_23-2149342625.jpg",
            },
            {
              title: "Full Valet",
              description: "Showroom ready",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-person-cleaning-car-exterior_23-2148194110.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
